### ISSUE TITLE
Неверно выводится класс?

### ISSUE THREAD

**Issue by kernusr** [Delo-Design/plg_system_radicalform_elements#4]
![изображение](https://user-images.githubusercontent.com/16020878/126081805-89129653-f06e-4b71-a81f-3b09265678c8.png)

На данный момент, класс `rf-input` выводится на уровне класса `.el-element`, что делает его бесполезным, для стилизации на уровне билдера

Если этот класс нужен только для стилизации, то лучше его и применить непосредственно к полю ввода, а не к контейнеру
Тогда и `.rf-label`, предложенный в https://github.com/Delo-Design/plg_system_radicalform_elements/issues/3 будет выглядеть логично

**Comment by progreccor** [comment]
да, конечно
