### ISSUE TITLE
Вкладка "Ещё" для hidden input

### ISSUE THREAD

**Issue by kernusr** [Delo-Design/plg_system_radicalform_elements#6]
![изображение](https://user-images.githubusercontent.com/16020878/126082860-278f4ea1-8d14-4a4c-a8b8-a71cdc0192fd.png)

Не хватает вкладки "ещё" для скрытого поля
Зачем?

1. Добавить data-атрибуты или задать id, для обработки на javascript
2. Добавить "имя" для отображения в билдере

**Comment by kernusr** [comment]
Сложно ориентироваться, какое поле за что отвечает
![изображение](https://user-images.githubusercontent.com/16020878/126082903-8bf150b1-fa6c-40a3-bea9-c4a67cb95b5c.png)

**Comment by progreccor** [comment]
ок

**Comment by progreccor** [comment]
вкладку "еще" я добавлю, но id будет для контейнера - так устроено в прошке

**Comment by kernusr** [comment]
Да этого достаточно. Больше полей в контейнер всеравно не воткнуть.

пн, 19 июл. 2021 г., 14:45 Vladimir Progreccor ***@***.***>:
